### ISSUE TITLE
Message box text is white but background is also white

### ISSUE THREAD

**Issue by shodanwashere** [alanmun/p5r-discord-theme#1]
The message text box's text is the same color as the text box's background, making text illegible while writing a message.
![image](https://github.com/alanmun/p5r-discord-theme/assets/74769749/afc18376-fd2d-4dba-8fbd-e93cd3979366)

Version: stable 264913 (ae72f64) Host 0.0.42 x64 Linux 64-bit (6.6.6-76060606-generic)

**Comment by alanmun** [comment]
If you have a minute, mind showing me what the entire screen looks like for you? Discord UI changes broke 80% of the theme for me, if I have free time I'm gonna try and patch the theme back to where it was (I was putting finishing touches on the theme when it broke). Curious how broken it looks on other people's devices. For me its just black and red coloring but almost all buttons and fonts and effects are gone

**Comment by alanmun** [comment]
This is fixed for all text boxes that I am aware of.
