### ISSUE TITLE
Emoji/Sticker/Gifs bug

### ISSUE THREAD

**Issue by CosmoDawg69** [alanmun/p5r-discord-theme#2]
A weird black bar appears when you select to use an emoji, sticker, or gif 

![Screenshot 2024-04-07 211957](https://github.com/alanmun/p5r-discord-theme/assets/166357969/bcbe1d40-7601-4a1e-9bf7-8a11b0245d8f)

**Comment by alanmun** [comment]
Fixed, thanks for letting me know
